### ISSUE TITLE
Breakage due to recent IO buffering change (missing .close?)

### ISSUE THREAD

**Issue by AlexDaniel** [zoffixznet/perl6-IO-MiddleMan#5]
Most tests of this module are currently broken on HEAD. See https://gist.github.com/cf4c6ee5ff9ad253af1c69d46d67e65f (only ``t/02-capture.t`` shown).

Bisectable points to https://github.com/rakudo/rakudo/commit/4b02b8aadcb47072bc87fb8be8069177b74cd59d

[Lumberjack](https://github.com/jonathanstowe/Lumberjack) and [Lumberjack::Dispatcher::Syslog](https://github.com/jonathanstowe/Lumberjack-Dispatcher-Syslog) depend on this module and therefore are shown as burnt in the toaster.

See also [RT #132030](https://rt.perl.org/Ticket/Display.html?id=132030).

Sister tickets:
* https://github.com/azawawi/perl6-ncurses/issues/16
* https://github.com/p6-css/CSS-Specification-p6/issues/2

**Comment by jjatria** [comment]
IO::MiddleMan tests pass currently on 2021.10 at least. And considering what was said in https://github.com/azawawi/perl6-ncurses/issues/16#issuecomment-330103600, I'd say this can be closed and #6 is not needed.
